# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3d9b0053564a175f1476ca84ac670822209f29e768b01eb2718bcaeb5201133ba9f799dd2776897c2f99644138b50711073df4ef7ec2b98e1c7b50788823e95

test:
  secret_key_base: c0684b73c15d28a8a073b1cd5780bf8b059a4cc294f7a484715ba2df2c0598a70d8721bf3c6620b3a7889130055b9180f0f0c4d80a33708f70c7211c6a4f4e2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
